definitions:
  model.Category:
    properties:
      color:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      type:
        type: string
      updated_at:
        type: string
    type: object
  model.CategoryUpdate:
    properties:
      color:
        type: string
      created_at:
        type: string
      description:
        type: string
      name:
        type: string
      type:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /category/{id}:
    get:
      consumes:
      - application/json
      description: Retorna os detalhes de uma categoria específica
      parameters:
      - description: ID da categoria
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "400":
          description: id da categoria é obrigatório
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: categoria não encontrada
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Buscar categoria por ID
      tags:
      - Category
  /category/create:
    post:
      consumes:
      - application/json
      description: Cria uma nova categoria para um usuário
      parameters:
      - description: Dados da categoria
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "400":
          description: corpo da requisição inválido
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Criar categoria
      tags:
      - Category
  /category/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Remove uma categoria existente pelo ID
      parameters:
      - description: ID da categoria
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: categoria deletada com sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: id da categoria é obrigatória
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: categoria não deletada
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Deletar categoria
      tags:
      - Category
  /category/update/{id}:
    put:
      consumes:
      - application/json
      description: Atualiza os dados de uma categoria existente
      parameters:
      - description: ID da categoria
        in: path
        name: id
        required: true
        type: string
      - description: Dados da categoria para atualização
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.CategoryUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "400":
          description: corpo da requisição inválido ou id ausente
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: erro ao atualizar categoria
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Atualizar categoria
      tags:
      - Category
swagger: "2.0"
